// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSchool_WebAPI.Data;

namespace SmartSchool_WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201024055754_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("SmartSchool_WebAPI.Models.Aluno", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("sobrenome")
                        .HasColumnType("TEXT");

                    b.Property<string>("telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nome = "Madalena",
                            sobrenome = "Puca",
                            telefone = "46380112"
                        },
                        new
                        {
                            id = 2,
                            nome = "Cristiniane",
                            sobrenome = "Queiroz",
                            telefone = "46395581"
                        },
                        new
                        {
                            id = 3,
                            nome = "Helenice",
                            sobrenome = "Dias",
                            telefone = "46390022"
                        },
                        new
                        {
                            id = 4,
                            nome = "Stetifânia",
                            sobrenome = "Zonodera",
                            telefone = "46385252"
                        },
                        new
                        {
                            id = 5,
                            nome = "Raphaela",
                            sobrenome = "Honória",
                            telefone = "46390114"
                        },
                        new
                        {
                            id = 6,
                            nome = "Manuela",
                            sobrenome = "Figueiredo",
                            telefone = "46340278"
                        },
                        new
                        {
                            id = 7,
                            nome = "Emily",
                            sobrenome = "Nascimento",
                            telefone = "46365540"
                        },
                        new
                        {
                            id = 8,
                            nome = "Melissa",
                            sobrenome = "Zonodera",
                            telefone = "46385252"
                        },
                        new
                        {
                            id = 9,
                            nome = "Isabela",
                            sobrenome = "Zonodera",
                            telefone = "46385252"
                        });
                });

            modelBuilder.Entity("SmartSchool_WebAPI.Models.AlunoDisciplina", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlunoId", "DisciplinaId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("AlunosDisciplinas");

                    b.HasData(
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 2
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 4
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 5
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 6
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 7
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 8
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 9
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 1
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 2
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 5
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 6
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 7
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 8
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 9
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 1
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 2
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 3
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 4
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 5
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 6
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 7
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 8
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 9
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 1
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 4
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 5
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 6
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 7
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 8
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 9
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 1
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 2
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 3
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 4
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 5
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 6
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 9
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 1
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 2
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 3
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 4
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 6
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 7
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 8
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 9
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 1
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 2
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 3
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 4
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 5
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 6
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 7
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 8
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 9
                        },
                        new
                        {
                            AlunoId = 8,
                            DisciplinaId = 1
                        },
                        new
                        {
                            AlunoId = 8,
                            DisciplinaId = 2
                        },
                        new
                        {
                            AlunoId = 8,
                            DisciplinaId = 3
                        },
                        new
                        {
                            AlunoId = 8,
                            DisciplinaId = 4
                        },
                        new
                        {
                            AlunoId = 8,
                            DisciplinaId = 5
                        },
                        new
                        {
                            AlunoId = 8,
                            DisciplinaId = 6
                        },
                        new
                        {
                            AlunoId = 8,
                            DisciplinaId = 7
                        },
                        new
                        {
                            AlunoId = 8,
                            DisciplinaId = 8
                        },
                        new
                        {
                            AlunoId = 8,
                            DisciplinaId = 9
                        },
                        new
                        {
                            AlunoId = 9,
                            DisciplinaId = 1
                        },
                        new
                        {
                            AlunoId = 9,
                            DisciplinaId = 2
                        },
                        new
                        {
                            AlunoId = 9,
                            DisciplinaId = 3
                        },
                        new
                        {
                            AlunoId = 9,
                            DisciplinaId = 4
                        },
                        new
                        {
                            AlunoId = 9,
                            DisciplinaId = 5
                        },
                        new
                        {
                            AlunoId = 9,
                            DisciplinaId = 6
                        },
                        new
                        {
                            AlunoId = 9,
                            DisciplinaId = 7
                        },
                        new
                        {
                            AlunoId = 9,
                            DisciplinaId = 8
                        },
                        new
                        {
                            AlunoId = 9,
                            DisciplinaId = 9
                        });
                });

            modelBuilder.Entity("SmartSchool_WebAPI.Models.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Disciplinas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "IIN001 - Inteligência de Negócios",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Nome = "ISI951-Sistemas Integrados de Gestão e Aplicações",
                            ProfessorId = 2
                        },
                        new
                        {
                            Id = 3,
                            Nome = "IGT002-Gestão de Tecnologia da Informação",
                            ProfessorId = 3
                        },
                        new
                        {
                            Id = 4,
                            Nome = "IAL004-Algoritmos",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 5,
                            Nome = "IRC108-Redes de Computadores",
                            ProfessorId = 5
                        },
                        new
                        {
                            Id = 6,
                            Nome = "GPJ002-Gestão de Projetos",
                            ProfessorId = 6
                        },
                        new
                        {
                            Id = 7,
                            Nome = "IES951-Engenharia de Software e Aplicações",
                            ProfessorId = 7
                        },
                        new
                        {
                            Id = 8,
                            Nome = "AGE001-Planejamento e Gestão Estratégica",
                            ProfessorId = 8
                        },
                        new
                        {
                            Id = 9,
                            Nome = "TAI001 - Tópicos Avançados em Tecnologia da Informação",
                            ProfessorId = 9
                        });
                });

            modelBuilder.Entity("SmartSchool_WebAPI.Models.Professor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nome = "Eduardo Lobo"
                        },
                        new
                        {
                            id = 2,
                            nome = "Almir Costa"
                        },
                        new
                        {
                            id = 3,
                            nome = "Cilene Araújo"
                        },
                        new
                        {
                            id = 4,
                            nome = "Ivaldo Franco"
                        },
                        new
                        {
                            id = 5,
                            nome = "Carlos Aragão"
                        },
                        new
                        {
                            id = 6,
                            nome = "Marcos Vasconcelos"
                        },
                        new
                        {
                            id = 7,
                            nome = "Edith Angulo"
                        },
                        new
                        {
                            id = 8,
                            nome = "Lélia Zambrano"
                        },
                        new
                        {
                            id = 9,
                            nome = "Geraldo Ribeiro"
                        });
                });

            modelBuilder.Entity("SmartSchool_WebAPI.Models.AlunoDisciplina", b =>
                {
                    b.HasOne("SmartSchool_WebAPI.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool_WebAPI.Models.Disciplina", "Disciplina")
                        .WithMany()
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchool_WebAPI.Models.Disciplina", b =>
                {
                    b.HasOne("SmartSchool_WebAPI.Models.Professor", "Professor")
                        .WithMany("Disciplinas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
